// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkOBZF2g1GHRkISAYrfieXgn6C1miar3A',
    appId: '1:40116935205:web:f8041d65ac8ac8ba717dcc',
    messagingSenderId: '40116935205',
    projectId: 'karya-manager',
    authDomain: 'karya-manager.firebaseapp.com',
    storageBucket: 'karya-manager.appspot.com',
    measurementId: 'G-0RD43D1BRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUwm7jSNTcG42xB7fdFrE3lvVf1UiaenA',
    appId: '1:40116935205:android:5579517b0174fbf3717dcc',
    messagingSenderId: '40116935205',
    projectId: 'karya-manager',
    storageBucket: 'karya-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHS4ujN3wY-QM7v-XdSCg3SX11Uja4CTY',
    appId: '1:40116935205:ios:4739a594b5a3dc88717dcc',
    messagingSenderId: '40116935205',
    projectId: 'karya-manager',
    storageBucket: 'karya-manager.appspot.com',
    iosBundleId: 'com.example.karyaManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHS4ujN3wY-QM7v-XdSCg3SX11Uja4CTY',
    appId: '1:40116935205:ios:4739a594b5a3dc88717dcc',
    messagingSenderId: '40116935205',
    projectId: 'karya-manager',
    storageBucket: 'karya-manager.appspot.com',
    iosBundleId: 'com.example.karyaManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkOBZF2g1GHRkISAYrfieXgn6C1miar3A',
    appId: '1:40116935205:web:72131317f0e37fb3717dcc',
    messagingSenderId: '40116935205',
    projectId: 'karya-manager',
    authDomain: 'karya-manager.firebaseapp.com',
    storageBucket: 'karya-manager.appspot.com',
    measurementId: 'G-YKN41MWPL6',
  );
}
